import type { RawBookPageDefinition } from "../../types";

export const csharpDeveloperPages = [
	{
		id: "csharp-overview",
		partId: "developers",
		path: "/docs/guides/csharp/overview",
		aliases: [
			"/docs/language/developers/csharp/overview",
			"/docs/guides/c-sharp/overview",
			"/docs/language/developers/c-sharp/overview",
			"/learn/language/developers/csharp/overview",
			"/learn/language/developers/c-sharp/overview",
		],
		sourcePath: "docs/what/language/developers/csharp/overview.md",
		questions: [],
	},
	{
		id: "csharp-values-methods-expressions",
		partId: "developers",
		path: "/docs/guides/csharp/values-methods-expressions",
		aliases: [
			"/docs/language/developers/csharp/values-methods-expressions",
			"/docs/guides/c-sharp/values-methods-expressions",
			"/docs/language/developers/c-sharp/values-methods-expressions",
			"/learn/language/developers/csharp/values-methods-expressions",
			"/learn/language/developers/c-sharp/values-methods-expressions",
		],
		sourcePath:
			"docs/what/language/developers/csharp/values-methods-expressions.md",
		questions: [],
	},
	{
		id: "csharp-blocks-control-flow",
		partId: "developers",
		path: "/docs/guides/csharp/blocks-control-flow",
		aliases: [
			"/docs/language/developers/csharp/blocks-control-flow",
			"/docs/guides/c-sharp/blocks-control-flow",
			"/docs/language/developers/c-sharp/blocks-control-flow",
			"/learn/language/developers/csharp/blocks-control-flow",
			"/learn/language/developers/c-sharp/blocks-control-flow",
		],
		sourcePath: "docs/what/language/developers/csharp/blocks-control-flow.md",
		questions: [],
	},
	{
		id: "csharp-variables-mutation",
		partId: "developers",
		path: "/docs/guides/csharp/variables-mutation",
		aliases: [
			"/docs/language/developers/csharp/variables-mutation",
			"/docs/guides/c-sharp/variables-mutation",
			"/docs/language/developers/c-sharp/variables-mutation",
			"/learn/language/developers/csharp/variables-mutation",
			"/learn/language/developers/c-sharp/variables-mutation",
		],
		sourcePath: "docs/what/language/developers/csharp/variables-mutation.md",
		questions: [],
	},
	{
		id: "csharp-records-classes-objects",
		partId: "developers",
		path: "/docs/guides/csharp/records-classes-objects",
		aliases: [
			"/docs/language/developers/csharp/records-classes-objects",
			"/docs/guides/c-sharp/records-classes-objects",
			"/docs/language/developers/c-sharp/records-classes-objects",
			"/learn/language/developers/csharp/records-classes-objects",
			"/learn/language/developers/c-sharp/records-classes-objects",
		],
		sourcePath:
			"docs/what/language/developers/csharp/records-classes-objects.md",
		questions: [],
	},
	{
		id: "csharp-collections-linq-pipelines",
		partId: "developers",
		path: "/docs/guides/csharp/collections-linq-pipelines",
		aliases: [
			"/docs/language/developers/csharp/collections-linq-pipelines",
			"/docs/guides/c-sharp/collections-linq-pipelines",
			"/docs/language/developers/c-sharp/collections-linq-pipelines",
			"/learn/language/developers/csharp/collections-linq-pipelines",
			"/learn/language/developers/c-sharp/collections-linq-pipelines",
		],
		sourcePath:
			"docs/what/language/developers/csharp/collections-linq-pipelines.md",
		questions: [],
	},
	{
		id: "csharp-null-option-result",
		partId: "developers",
		path: "/docs/guides/csharp/null-option-result",
		aliases: [
			"/docs/language/developers/csharp/null-option-result",
			"/docs/guides/c-sharp/null-option-result",
			"/docs/language/developers/c-sharp/null-option-result",
			"/learn/language/developers/csharp/null-option-result",
			"/learn/language/developers/c-sharp/null-option-result",
		],
		sourcePath: "docs/what/language/developers/csharp/null-option-result.md",
		questions: [],
	},
	{
		id: "csharp-exceptions-effects",
		partId: "developers",
		path: "/docs/guides/csharp/exceptions-effects",
		aliases: [
			"/docs/language/developers/csharp/exceptions-effects",
			"/docs/guides/c-sharp/exceptions-effects",
			"/docs/language/developers/c-sharp/exceptions-effects",
			"/learn/language/developers/csharp/exceptions-effects",
			"/learn/language/developers/c-sharp/exceptions-effects",
		],
		sourcePath: "docs/what/language/developers/csharp/exceptions-effects.md",
		questions: [],
	},
	{
		id: "csharp-unions-pattern-matching",
		partId: "developers",
		path: "/docs/guides/csharp/unions-pattern-matching",
		aliases: [
			"/docs/language/developers/csharp/unions-pattern-matching",
			"/docs/guides/c-sharp/unions-pattern-matching",
			"/docs/language/developers/c-sharp/unions-pattern-matching",
			"/learn/language/developers/csharp/unions-pattern-matching",
			"/learn/language/developers/c-sharp/unions-pattern-matching",
		],
		sourcePath:
			"docs/what/language/developers/csharp/unions-pattern-matching.md",
		questions: [],
	},
	{
		id: "csharp-generics-interfaces-laws",
		partId: "developers",
		path: "/docs/guides/csharp/generics-interfaces-laws",
		aliases: [
			"/docs/language/developers/csharp/generics-interfaces-laws",
			"/docs/guides/c-sharp/generics-interfaces-laws",
			"/docs/language/developers/c-sharp/generics-interfaces-laws",
			"/learn/language/developers/csharp/generics-interfaces-laws",
			"/learn/language/developers/c-sharp/generics-interfaces-laws",
		],
		sourcePath:
			"docs/what/language/developers/csharp/generics-interfaces-laws.md",
		questions: [],
	},
	{
		id: "csharp-extension-methods-and-calls",
		partId: "developers",
		path: "/docs/guides/csharp/extension-methods-and-calls",
		aliases: [
			"/docs/language/developers/csharp/extension-methods-and-calls",
			"/docs/guides/c-sharp/extension-methods-and-calls",
			"/docs/language/developers/c-sharp/extension-methods-and-calls",
			"/learn/language/developers/csharp/extension-methods-and-calls",
			"/learn/language/developers/c-sharp/extension-methods-and-calls",
		],
		sourcePath:
			"docs/what/language/developers/csharp/extension-methods-and-calls.md",
		questions: [],
	},
	{
		id: "csharp-namespaces-modules-packages",
		partId: "developers",
		path: "/docs/guides/csharp/namespaces-modules-packages",
		aliases: [
			"/docs/language/developers/csharp/namespaces-modules-packages",
			"/docs/guides/c-sharp/namespaces-modules-packages",
			"/docs/language/developers/c-sharp/namespaces-modules-packages",
			"/learn/language/developers/csharp/namespaces-modules-packages",
			"/learn/language/developers/c-sharp/namespaces-modules-packages",
		],
		sourcePath:
			"docs/what/language/developers/csharp/namespaces-modules-packages.md",
		questions: [],
	},
	{
		id: "csharp-testing-tooling",
		partId: "developers",
		path: "/docs/guides/csharp/testing-tooling",
		aliases: [
			"/docs/language/developers/csharp/testing-tooling",
			"/docs/guides/c-sharp/testing-tooling",
			"/docs/language/developers/c-sharp/testing-tooling",
			"/learn/language/developers/csharp/testing-tooling",
			"/learn/language/developers/c-sharp/testing-tooling",
		],
		sourcePath: "docs/what/language/developers/csharp/testing-tooling.md",
		questions: [],
	},
	{
		id: "csharp-unsafe-interop-ffi",
		partId: "developers",
		path: "/docs/guides/csharp/unsafe-interop-ffi",
		aliases: [
			"/docs/language/developers/csharp/unsafe-interop-ffi",
			"/docs/guides/c-sharp/unsafe-interop-ffi",
			"/docs/language/developers/c-sharp/unsafe-interop-ffi",
			"/learn/language/developers/csharp/unsafe-interop-ffi",
			"/learn/language/developers/c-sharp/unsafe-interop-ffi",
		],
		sourcePath: "docs/what/language/developers/csharp/unsafe-interop-ffi.md",
		questions: [],
	},
] satisfies readonly RawBookPageDefinition[];
