import type { BookSectionDefinition } from "./types";

export const bookSections = [
	{
		id: "developers-c99",
		partId: "developers",
		path: "/docs/guides/c99",
		aliases: [
			"/docs/guides/c",
			"/learn/guides/c",
			"/docs/guides/c",
			"/learn/guides/c",
			"/docs/language/developers/c",
			"/learn/language/developers/c",
		],
		title: "Musi for C Developers",
		description:
			"Translate C99 habits into Musi's expression, data, effect, and FFI model.",
		group: "Musi for Developers",
		section: "C Developers",
		order: 1,
		slug: "c99",
		summary:
			"C99-specific contrasts for functions, structs, arrays, pointers, errors, packages, tests, and native boundaries.",
	},
	{
		id: "developers-cpp17",
		partId: "developers",
		path: "/docs/guides/cpp17",
		aliases: [
			"/docs/guides/cpp",
			"/learn/guides/cpp",
			"/docs/guides/c-plus-plus",
			"/learn/guides/c-plus-plus",
			"/docs/guides/c-cpp",
			"/learn/guides/c-cpp",
			"/docs/guides/c-and-cpp",
			"/learn/guides/c-and-cpp",
			"/docs/guides/cpp",
			"/learn/guides/cpp",
			"/docs/guides/c-plus-plus",
			"/learn/guides/c-plus-plus",
			"/docs/guides/c-cpp",
			"/learn/guides/c-cpp",
			"/docs/guides/c-and-cpp",
			"/learn/guides/c-and-cpp",
			"/docs/language/developers/cpp",
			"/learn/language/developers/cpp",
			"/docs/language/developers/c-plus-plus",
			"/learn/language/developers/c-plus-plus",
			"/docs/language/developers/c-cpp",
			"/learn/language/developers/c-cpp",
		],
		title: "Musi for C++ Developers",
		description:
			"Translate C++17 habits into Musi's expression, data, effect, and FFI model.",
		group: "Musi for Developers",
		section: "C++ Developers",
		order: 2,
		slug: "cpp17",
		summary:
			"C++17-specific contrasts for functions, records, variants, templates, packages, tests, and native boundaries.",
	},
	{
		id: "developers-rust",
		partId: "developers",
		path: "/docs/guides/rust",
		aliases: [
			"/docs/guides/rust",
			"/docs/language/developers/rust-guide",
			"/learn/language/developers/rust-guide",
		],
		title: "Musi for Rust Developers",
		description:
			"Translate Rust 2024 edition (1.85+) habits into Musi's expression, data, abstraction, and mutation model.",
		group: "Musi for Developers",
		section: "Rust Developers",
		order: 9,
		slug: "rust",
		summary:
			"Rust-specific contrasts for mutation, data, traits, effects, and native boundaries.",
	},
	{
		id: "developers-csharp",
		partId: "developers",
		path: "/docs/guides/csharp",
		aliases: [
			"/docs/guides/c-sharp",
			"/learn/guides/c-sharp",
			"/docs/guides/csharp",
			"/docs/guides/c-sharp",
			"/learn/guides/c-sharp",
			"/docs/language/developers/csharp",
			"/docs/language/developers/c-sharp",
			"/learn/language/developers/csharp",
			"/learn/language/developers/c-sharp",
		],
		title: "Musi for C# Developers",
		description:
			"Translate .NET 8.0 and C# 12.0 habits into Musi's expression, data, effect, and package model.",
		group: "Musi for Developers",
		section: "C# Developers",
		order: 3,
		slug: "csharp",
		summary:
			"C#-specific contrasts for methods, records, collections, nullability, exceptions, interfaces, packages, tests, and native boundaries.",
	},
	{
		id: "developers-go",
		partId: "developers",
		path: "/docs/guides/go",
		aliases: [
			"/docs/guides/go",
			"/learn/guides/go",
			"/docs/language/developers/go",
			"/learn/language/developers/go",
		],
		title: "Musi for Go Developers",
		description:
			"Translate Go 1.26.2 habits into Musi's expression, data, effect, and package model.",
		group: "Musi for Developers",
		section: "Go Developers",
		order: 4,
		slug: "go",
		summary:
			"Go-specific contrasts for functions, structs, slices, nil, errors, concurrency, interfaces, packages, tests, and native boundaries.",
	},
	{
		id: "developers-javascript-typescript",
		partId: "developers",
		path: "/docs/guides/javascript-typescript",
		aliases: [
			"/docs/guides/javascript",
			"/docs/guides/typescript",
			"/docs/guides/javascript",
			"/docs/guides/typescript",
			"/docs/language/developers/javascript",
			"/docs/language/developers/typescript",
			"/learn/language/developers/javascript",
			"/learn/language/developers/typescript",
		],
		title: "Musi for JavaScript and TypeScript Developers",
		description:
			"Translate ES6 JavaScript runtime habits and TypeScript 5.9 type habits into Musi.",
		group: "Musi for Developers",
		section: "JavaScript and TypeScript Developers",
		order: 6,
		slug: "javascript-typescript",
		summary:
			"Side-by-side contrasts for objects, functions, unions, generics, promises, modules, and tests.",
	},
	{
		id: "developers-lua",
		partId: "developers",
		path: "/docs/guides/lua",
		aliases: [
			"/docs/guides/lua",
			"/learn/guides/lua",
			"/docs/language/developers/lua",
			"/learn/language/developers/lua",
		],
		title: "Musi for Lua Developers",
		description:
			"Translate Lua 5.4.8 habits into Musi's expression, data, effect, and package model.",
		group: "Musi for Developers",
		section: "Lua Developers",
		order: 7,
		slug: "lua",
		summary:
			"Lua-specific contrasts for locals, functions, tables, nil, errors, coroutines, metatables, modules, tests, and native boundaries.",
	},
	{
		id: "developers-java",
		partId: "developers",
		path: "/docs/guides/java",
		aliases: [
			"/docs/guides/java",
			"/learn/guides/java",
			"/docs/language/developers/java",
			"/learn/language/developers/java",
		],
		title: "Musi for Java Developers",
		description:
			"Translate Java 17 habits into Musi's expression, data, effect, and package model.",
		group: "Musi for Developers",
		section: "Java Developers",
		order: 5,
		slug: "java",
		summary:
			"Java-specific contrasts for methods, records, collections, nullability, exceptions, sealed types, interfaces, packages, tests, and native boundaries.",
	},
	{
		id: "developers-python",
		partId: "developers",
		path: "/docs/guides/python",
		aliases: [
			"/docs/guides/python",
			"/docs/language/developers/python",
			"/learn/language/developers/python",
		],
		title: "Musi for Python Developers",
		description:
			"Translate Python 3.14 habits into Musi's expression, data, effect, and package model.",
		group: "Musi for Developers",
		section: "Python Developers",
		order: 8,
		slug: "python",
		summary:
			"Python-specific contrasts for functions, blocks, objects, collections, errors, protocols, modules, tests, and native boundaries.",
	},
] satisfies readonly BookSectionDefinition[];
